language: csharp
solution: src/Void.sln
sudo: false
script:
- ./build.sh
notifications:
  slack:
    secure: ClFSQvKGQe0JN8iircAYscyYZT0r+AFn9iUdd3WctxxG6jQTZGkjeAd4XvecTarlhGU/xXe13m2E2PLY7QN3AJIkELdp5HppoM2ih+dz8kGQzTYBVKMXHf533biMQrSgDzqAzUpsLuWh09Yu85LTfrQuqoSA5vsUuGIOzAzgdJg=
