version: 0.0.0.{build}
build:
  verbosity: minimal
test:
  assemblies: '**\*.Spec.dll'
notifications:
- provider: Slack
  auth_token:
    secure: Nmuk9tA9cwOJPNEGhvsKrMEQdrLkQet5dbpxIdh4N9GGvmio2pmM/ChnEBRBstND
  channel: vim_and_text_editors
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true