version: 0.0.2.{build}
build_script:
- ./build.bat WinCIBuild
test: off
artifacts:
- path: build/Void.msi
  name: MSI installer
notifications:
- provider: Slack
  auth_token:
    secure: Nmuk9tA9cwOJPNEGhvsKrMEQdrLkQet5dbpxIdh4N9GGvmio2pmM/ChnEBRBstND
  channel: vim_and_text_editors
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
